/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todolist_java;

//import java.util.ArrayList;


public class App {
   

    public static void main(String[] args) {
       
        ToDoList todoForToday = new ToDoList();

        todoForToday.addTask("shopping");

        todoForToday.addTask("doctor");

        todoForToday.addTask("cleaning");

        ToDoList todoForTomorrow = new ToDoList();

        todoForTomorrow.addTask("studying");

        todoForTomorrow.addTask("N64");

        todoForTomorrow.addTask("PlayStation");


       
        System.out.println(todoForToday.getTasks());

        System.out.println(todoForTomorrow.getTasks());
    }
}
